/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReadyRouteImport } from './routes/ready'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BulkVerifyRouteImport } from './routes/bulk-verify'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewExamIdRouteImport } from './routes/review.$examId'
import { Route as GuidanceExamIdRouteImport } from './routes/guidance.$examId'
import { Route as EligibilityExamIdRouteImport } from './routes/eligibility.$examId'
import { Route as ChecklistExamIdRouteImport } from './routes/checklist.$examId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkVerifyRoute = BulkVerifyRouteImport.update({
  id: '/bulk-verify',
  path: '/bulk-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewExamIdRoute = ReviewExamIdRouteImport.update({
  id: '/review/$examId',
  path: '/review/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidanceExamIdRoute = GuidanceExamIdRouteImport.update({
  id: '/guidance/$examId',
  path: '/guidance/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityExamIdRoute = EligibilityExamIdRouteImport.update({
  id: '/eligibility/$examId',
  path: '/eligibility/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistExamIdRoute = ChecklistExamIdRouteImport.update({
  id: '/checklist/$examId',
  path: '/checklist/$examId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bulk-verify': typeof BulkVerifyRoute
  '/dashboard': typeof DashboardRoute
  '/discovery': typeof DiscoveryRoute
  '/errors': typeof ErrorsRoute
  '/exams': typeof ExamsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/ready': typeof ReadyRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/upload': typeof UploadRoute
  '/verify': typeof VerifyRoute
  '/checklist/$examId': typeof ChecklistExamIdRoute
  '/eligibility/$examId': typeof EligibilityExamIdRoute
  '/guidance/$examId': typeof GuidanceExamIdRoute
  '/review/$examId': typeof ReviewExamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bulk-verify': typeof BulkVerifyRoute
  '/dashboard': typeof DashboardRoute
  '/discovery': typeof DiscoveryRoute
  '/errors': typeof ErrorsRoute
  '/exams': typeof ExamsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/ready': typeof ReadyRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/upload': typeof UploadRoute
  '/verify': typeof VerifyRoute
  '/checklist/$examId': typeof ChecklistExamIdRoute
  '/eligibility/$examId': typeof EligibilityExamIdRoute
  '/guidance/$examId': typeof GuidanceExamIdRoute
  '/review/$examId': typeof ReviewExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bulk-verify': typeof BulkVerifyRoute
  '/dashboard': typeof DashboardRoute
  '/discovery': typeof DiscoveryRoute
  '/errors': typeof ErrorsRoute
  '/exams': typeof ExamsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/ready': typeof ReadyRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/upload': typeof UploadRoute
  '/verify': typeof VerifyRoute
  '/checklist/$examId': typeof ChecklistExamIdRoute
  '/eligibility/$examId': typeof EligibilityExamIdRoute
  '/guidance/$examId': typeof GuidanceExamIdRoute
  '/review/$examId': typeof ReviewExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bulk-verify'
    | '/dashboard'
    | '/discovery'
    | '/errors'
    | '/exams'
    | '/privacy'
    | '/profile'
    | '/ready'
    | '/settings'
    | '/studio'
    | '/upload'
    | '/verify'
    | '/checklist/$examId'
    | '/eligibility/$examId'
    | '/guidance/$examId'
    | '/review/$examId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bulk-verify'
    | '/dashboard'
    | '/discovery'
    | '/errors'
    | '/exams'
    | '/privacy'
    | '/profile'
    | '/ready'
    | '/settings'
    | '/studio'
    | '/upload'
    | '/verify'
    | '/checklist/$examId'
    | '/eligibility/$examId'
    | '/guidance/$examId'
    | '/review/$examId'
  id:
    | '__root__'
    | '/'
    | '/bulk-verify'
    | '/dashboard'
    | '/discovery'
    | '/errors'
    | '/exams'
    | '/privacy'
    | '/profile'
    | '/ready'
    | '/settings'
    | '/studio'
    | '/upload'
    | '/verify'
    | '/checklist/$examId'
    | '/eligibility/$examId'
    | '/guidance/$examId'
    | '/review/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BulkVerifyRoute: typeof BulkVerifyRoute
  DashboardRoute: typeof DashboardRoute
  DiscoveryRoute: typeof DiscoveryRoute
  ErrorsRoute: typeof ErrorsRoute
  ExamsRoute: typeof ExamsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReadyRoute: typeof ReadyRoute
  SettingsRoute: typeof SettingsRoute
  StudioRoute: typeof StudioRoute
  UploadRoute: typeof UploadRoute
  VerifyRoute: typeof VerifyRoute
  ChecklistExamIdRoute: typeof ChecklistExamIdRoute
  EligibilityExamIdRoute: typeof EligibilityExamIdRoute
  GuidanceExamIdRoute: typeof GuidanceExamIdRoute
  ReviewExamIdRoute: typeof ReviewExamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-verify': {
      id: '/bulk-verify'
      path: '/bulk-verify'
      fullPath: '/bulk-verify'
      preLoaderRoute: typeof BulkVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$examId': {
      id: '/review/$examId'
      path: '/review/$examId'
      fullPath: '/review/$examId'
      preLoaderRoute: typeof ReviewExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidance/$examId': {
      id: '/guidance/$examId'
      path: '/guidance/$examId'
      fullPath: '/guidance/$examId'
      preLoaderRoute: typeof GuidanceExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility/$examId': {
      id: '/eligibility/$examId'
      path: '/eligibility/$examId'
      fullPath: '/eligibility/$examId'
      preLoaderRoute: typeof EligibilityExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist/$examId': {
      id: '/checklist/$examId'
      path: '/checklist/$examId'
      fullPath: '/checklist/$examId'
      preLoaderRoute: typeof ChecklistExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BulkVerifyRoute: BulkVerifyRoute,
  DashboardRoute: DashboardRoute,
  DiscoveryRoute: DiscoveryRoute,
  ErrorsRoute: ErrorsRoute,
  ExamsRoute: ExamsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReadyRoute: ReadyRoute,
  SettingsRoute: SettingsRoute,
  StudioRoute: StudioRoute,
  UploadRoute: UploadRoute,
  VerifyRoute: VerifyRoute,
  ChecklistExamIdRoute: ChecklistExamIdRoute,
  EligibilityExamIdRoute: EligibilityExamIdRoute,
  GuidanceExamIdRoute: GuidanceExamIdRoute,
  ReviewExamIdRoute: ReviewExamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
